### ISSUE TITLE
Home page enhancement

### ISSUE THREAD

**Issue by BrianSo** [briansostudio/teamform#1]
1. Home page can submit on user pressed enter
2. The text of "create event or mange your event" is not easy to understand for participant

As most user will be participant, I suggest:
- use "Enter event" as the primary button
- use "Create Event as the secondary button"
- Check event existence when input change. If the event exists, replace "Create event" by "Manage Event"

**Comment by leolo322** [comment]
I think it will be good to show a list of events in the home page so that the users can quickly look for the event they want to join. They can use the "Create event" to create a new event; and manage event to look for the teams/details of a certain event.

**Comment by BrianSo** [comment]
Yeah, but the list should be somehow small to let users remain focus on the event selection. We can show autocomplete when user typing event name

**Comment by leolo322** [comment]
auto-complete is a good idea
