### ISSUE TITLE
Deadline counter discussion

### ISSUE THREAD

**Issue by clementf2b** [briansostudio/teamform#12]
Are there any further actions for our system when the deadline of the event is reached?

**Comment by ttchiuaa** [comment]
Send notification to the team?
But it seems sending message after the deadline is meaningless...

**Comment by clementf2b** [comment]
Like people can create a deadline alert for people who enters the app.

**Comment by 0xinterface** [comment]
where should the deadline be placed? inside each team page or right in front of the center of the event page?

**Comment by BrianSo** [comment]
I think just on the event page is enough. May be we can create components for team page later

**Comment by Ag47** [comment]
showing total number of team or participants had registered for the event?

**Comment by clementf2b** [comment]
@Ag47 I think this question can create a new issue to discuss . This should be an enhancement for the team list.
