### ISSUE TITLE
cannot test Event.vue and EventAction.vue

### ISSUE THREAD

**Issue by BrianSo** [briansostudio/teamform#13]
There is one big problem that the firebaseRefs cannot be injected so Event.vue and EventAction.vue cannot be tested.

@narwhlae I know you are working on the vuex implementation of backend and that will fix this issue, but please also make your vuex implementation testable, i.e. all the dependency can be mocked and injected.

**Comment by 0xinterface** [comment]
This issue will resolve after flux implementation takes effect in the near future
