### ISSUE TITLE
Supplementary API request

### ISSUE THREAD

**Issue by 0xinterface** [briansostudio/teamform#24]
@BrianSo @Ag47 @clementf2b @ttchiuaa @singspiel @leolo322 

Please be notified that you are required to submit your request on your ViewModel data structure requirement, you can write down your request down below.

**Comment by Ag47** [comment]
Radar Skillset attribute API request

assuming the radarskill is input by event organizer
#8 

Sample JSON Response

``` json
{
  "Users": [
    {
      "label": "John",
      "Radar": [
        65, 59, 90, 81, 56, 55
      ]
    },
    {
      "label": "Sara",
      "Radar": [
        65, 59, 90, 81, 56, 55
      ]
    }

  ]
}
```
