### ISSUE TITLE
make a discussion board

### ISSUE THREAD

**Issue by ttchiuaa** [briansostudio/teamform#3]
create a discussion board in event page

**Comment by BrianSo** [comment]
Do you mean a new feature? I think it is a good idea, but we should stick with what we have decided first, as time is limited while discussion board is a relatively large scale feature.

**Comment by ttchiuaa** [comment]
maybe just make a simple one with name and message only for fast chat?

**Comment by BrianSo** [comment]
I saw you have done something for it. I don't want to throw you work. So now it's up to you to get it included.
