### ISSUE TITLE
Main page layout

### ISSUE THREAD

**Issue by 0xinterface** [briansostudio/teamform#33]
Please vote for the home page behavior as described follow,

1. Enter home page, presented with two buttons -> (Create Event) : (Load Event) [After load event is click user will be presented with options to either go directly into the the event page, or admin will be presented will password based authentication to be directed to event admin page]
2. Enter home page, presented with two buttons -> (Join Event) : (I am event organizer)
[After I am event organizer is click, it will be prompted to either create an event or manage an event]

**Comment by ttchiuaa** [comment]
(2)

**Comment by clementf2b** [comment]
(1)
