### ISSUE TITLE
Questions about login page

### ISSUE THREAD

**Issue by clementf2b** [briansostudio/teamform#4]
1. Where will we place the login function?
2. How many types of account do we need in this project?
3. How many types of login method do we need in each types of account?

**Comment by 0xinterface** [comment]
for Q1. login function should be placed at the home page as a modal dialog after you key in the event name at clicked on the "enter button"

for Q3. the types of account can be binded to their social network account, separate authentication such as app-binded / event-binded one time account can be decide whether it should be put in the implementation
