### ISSUE TITLE
Problem in showing popup

### ISSUE THREAD

**Issue by ttchiuaa** [briansostudio/teamform#54]
When it is empty in the textarea and if a user click the send button, a popup warning is supposed to appear. however, there is no action at all.
Here is the code and console error showing "message is not defined"
Is there anyone have idea to solve my problem?

![screenshot from 2016-11-15 12-55-18](https://cloud.githubusercontent.com/assets/16485834/20293691/686ffb6a-ab33-11e6-9e4c-6d23bb799119.png)
![screenshot from 2016-11-15 12-58-22](https://cloud.githubusercontent.com/assets/16485834/20293699/70307618-ab33-11e6-97c4-b8acf823b4ec.png)
![screenshot from 2016-11-15 13-00-56](https://cloud.githubusercontent.com/assets/16485834/20293711/9e047e68-ab33-11e6-8388-b22d9cbe8f5d.png)

**Comment by clementf2b** [comment]
message should change to this.message?

**Comment by BrianSo** [comment]
Yes

**Comment by BrianSo** [comment]
Unlike c++/Java, JavaScript always requires this keyword
