### ISSUE TITLE
Radar Label Issue

### ISSUE THREAD

**Issue by Ag47** [briansostudio/teamform#6]
the label for radar should be constant or modifiable?

current label:
```
labels: ["Web", "Android", "iOS", "UI Design", "Server", "Custom 1", "Custom 2"]
```

**Comment by BrianSo** [comment]
This depends how we are going to release our features, I think we can use phased approach to release a constant version. Then make enhancement on it later.

**Comment by Ag47** [comment]
OK, i created a pull request #7 .
Lets review it.
