### ISSUE TITLE
User data schema Discussion

### ISSUE THREAD

**Issue by Ag47** [briansostudio/teamform#8]
what is the data schema in database?
As I need to implement the feature for the chart
@singspiel @BrianSo @ttchiuaa @narwhlae @leolo322

**Comment by Ag47** [comment]
Skill set label will have 3 options to input
1. input by event organizer 👍 
2. input by team leader 😄  
3. input by all member 🎉 

which one is better? Have a vote by picking a reaction

**Comment by clementf2b** [comment]
Will they input the skill set when they register the account?

**Comment by Ag47** [comment]
yes if we are using the 2nd or 3rd option

**Comment by BrianSo** [comment]
for 1, event organizer specify what skill should the user input, user input the skill set when they register
for 2, team leader specify what skill should the user input, user input the skill set when they request to join a team
for 3, user input the skill set whenever, whatever they want
