### ISSUE TITLE
Deadline counter always think the event is ended

### ISSUE THREAD

**Issue by BrianSo** [briansostudio/teamform#85]
I disabled the swal statement so it will not border us. Please fix the issue before enabling the swal statement. @clementf2b

**Comment by clementf2b** [comment]
What is the meaning? Any example? Perhaps the date input is wrong?
I am using the following format to test before
`<Countdown date="16 June 2016 03:02:01 GMT"></countdown>`

**Comment by clementf2b** [comment]
Oh I know what you mean
