### ISSUE TITLE
WeeklySchedule component display Issue

### ISSUE THREAD

**Issue by Ag47** [briansostudio/teamform#87]
WeeklySchedule can not display properly while in Element el-tab tag.
But it is fine outside the el-tabs tag.
Even I add the width and height attributes into the the tag, it still invisible.
Help~~~

**Comment by clementf2b** [comment]
Perhaps the semantic UI in weeklySchedule crashed with the element ?

**Comment by BrianSo** [comment]
@Ag47 Maybe you could ignore this issue first. I will try to figure out the problem.

**Comment by BrianSo** [comment]
I used a workaround which place the WeeklySchedule outside the tab and detect tab clicking to hide and show it accordingly.

**Comment by Ag47** [comment]
thanks
