### ISSUE TITLE
[Important] Account bind to Event or the App?

### ISSUE THREAD

**Issue by BrianSo** [briansostudio/teamform#9]
Should we register different account for different events, or one account for any event?
Please vote by reaction

1)  bind to event 👍 
2)  bind to app 😄 

For 1) bind to event. user will first select an event before we log in to the event. And input our information for each event. The user profile can have different data for each event.
 - Pros: can have different skill radar chart for different event
 - Cons: User need to input many times for different events; Probably cannot uses firebase built in authentication.

For 2) bind to app. We use the same user data for each event. which might not suitable for all events.
 - Pros: User will not have to input their information again for another event
 - Cons: Implementation might be complicated If we want user to have different skill radar chart for different event

**Comment by BrianSo** [comment]
@narwhlae @Ag47 @clementf2b @ttchiuaa @singspiel @leolo322

**Comment by 0xinterface** [comment]
@BrianSo for 1. , the cons isn't really convincing because it is entire up to the user interface to decide whether the input process will be tedious. e.g we can apply slider at scale for each skill set input to minimize the input effort.

**Comment by BrianSo** [comment]
@narwhlae 
It's not only radar data, but also his name, his self introduction, schedule and so on.

But I am now considering to use 1) as time is limited
